### ISSUE TITLE
Using different music and sound effects from quest using TGE 5.2

### ISSUE THREAD

**Issue by Darkerus** [roginvs/space-rangers-quest#25]
Im trying to make my own quest using TGE 5.2.10 - and found that if I use sound effect field or music field (in TGE its like Image 
field), nothing changes in game in your app. That means that i cant use sound effect by music folder or change the music in special locations.

**Comment by roginvs** [comment]
Ok, it is quite clear what should happen if we have to play sound effect.
But how music change should work? What should happen when track is ended, should it play it from the beginning or play random track from tracks pool?

**Comment by Darkerus** [comment]
I think - play it from the beginning. To make more carefull sound design.
