### ISSUE TITLE
повышение доступности плеера для людей с ограничениями зрения

### ISSUE THREAD

**Issue by Daniil-Gusev** [roginvs/space-rangers-quest#49]
Протестировано на iphone SE ios 15.3.1, программа чтения с экрана voiceover.
В данный момент кнопки в плеере не помечены, иными словами программы чтения с экрана (скринридеры) читают их просто как "кнопка" без каких либо дополнительных обозначений. Это очень затрудняет взаимодействие с плеером и узнать, что какая кнопка делает можно лишь интуитивно, нажав на нужную кнопку. начать можно с интерфейса игр после их запуска: где-то вверху, до текста самой игры, находятся 4 никак не обозначенных кнопки. Так же можно отметить кнопку на главном экране плеера, открывающую меню с редактором, рекордами итп. Редактор, кстати, тоже представляет собой набор непомеченных кнопок.

**Comment by roginvs** [comment]
Добавил aria-label на кнопки в плеере, добавил на редактор. Жду обратной связи

**Comment by Daniil-Gusev** [comment]
> Добавил aria-label на кнопки в плеере, добавил на редактор. Жду обратной связи

Стало в самом деле гораздо удобнее, большое спасибо. так же можно пометить кнопку, открывающую меню приложения, которая находится там же, где список квестов, и кнопку технической поддержки, тогда станет совсем хорошо.

**Comment by roginvs** [comment]
Добавил `aria-label` на гамбургер. На кнопку техподдержки чуть сложней будет добавить, это отдельный скрипт делает

**Comment by roginvs** [comment]
Есть ли что-то еще что можно улучшить (кроме редактора)?

**Comment by Daniil-Gusev** [comment]
Думаю, что вопрос полностью решен, и весь функционал плеера доступен в полной мере для пользователей программ экранного доступа.
