### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by daivers** [roginvs/space-rangers-quest#53]
Скачал репозиторий. Сборку произвел четко по инструкции. Собрал. Но при переходе пишет что отсутствует json файл built-web/data/index.json. Думаю ну не беда, скопировал его с вашего сайта. Запустилось. Дальше смотрю в папке built-web/data/qm вроде как должны были подтянуться квесты которые я добавлял при сборке, но там пусто. В итоге думаю не беда, добавлю их в ручную. Но они у меня разрешения .gm а в джейсоне прописаны gm.gz. Что за формат gz я не нашел в интернете. Опять неудача. Думаю ладно загружу в облако. Пытаюсь залогиниться либо через гугл либо гитхаб и ни чего не происходит. Помогите пожалуйста.

**Comment by roginvs** [comment]
Самое простое - это скачать полностью папку `borrowed` из https://gitlab.com/spacerangers/spacerangers.gitlab.io/ и затем запустить `npm run pack-game-data` (этот скрипт запакует ресурсы и положит в `build-web`)

**Comment by roginvs** [comment]
(Формат `.qm.gz`/`.qmm.gz` это просто обычный `qm/qmm` только запаковынный в gzip)

**Comment by daivers** [comment]
спасибо, сейчас буду пробовать

**Comment by roginvs** [comment]
Получилось? Можно тикет закрывать?

**Comment by daivers** [comment]
Да, большое спасибо. Все получилось.
