### ISSUE TITLE
Сортировка: странное поведение спорных стрелок, действительно так в живой игре?

### ISSUE THREAD

**Issue by Mercury13** [roginvs/space-rangers-quest#71]
1. Квест «Сортировка».
2. Принять какой-то груз на какой-то путь.
3. Вывезти этот путь маневровыми паровозами (одним или несколькими).
4. С вероятностью 50% оказывается, что на этом пути 0 вагонов какого-то груза. Если принять на этот путь другой груз, получаешь взыскание.

Действительно так в «живой» игре? — я не проверял.
Связано с поведением спорных стрелок.

**Comment by roginvs** [comment]
Я проверил на TGE 5.2.10 и там такая же проблема. В квесте на вот этих вот переходах не выключен переход P55 когда должен сработать другой спорный. Потому и вероятость 50% что очистит груз если там 0 вагонов.
![image](https://github.com/roginvs/space-rangers-quest/assets/6670512/6408a2f2-f878-4e17-b1e3-d9d2c6f45409)

**Comment by roginvs** [comment]
Наверное самое простое будет приоритет выставить большой (больше 100) для остальных спорных чтобы когда они активны то P55 не был вариантом вообще. Ну или добавить большое логическое условие на P55
